version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_USER_API_URL=http://localhost:5001
      # Auth0 configuration with explicit values
      - AUTH0_SECRET=942db54f9c7cea41a6ecf89a37f004cbe2fed1cd35fbf7a3430752c0b1ac2361
      - AUTH0_BASE_URL=http://localhost:3000
      - AUTH0_ISSUER_BASE_URL=https://dev-iy154pu2gh5wsjh8.eu.auth0.com
      - AUTH0_CLIENT_ID=aQHzUroFmLvkTToLdXq9oThLlBWSv4zx
      - AUTH0_CLIENT_SECRET=4iIMiTqb8JMfkVZpQzjl0hudPYtGpO_pwoR9l24LSNgOHjo9_sa4oG75MuhYsAh_
    volumes:
      - ./.env:/app/.env 